FROM maven:3.8.3-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:17.0.1-jdk-slim
COPY --from=build /target/connection-checker-0.0.1-SNAPSHOT.jar connection-checker.jar
EXPOSE 8080
ENTRYPOINT [ "java","-jar","connection-checker.jar" ]